// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Test = require("./Test.bs.js");

var greet_name = Test.greet_name;

var NetworkRe;

exports.greet_name = greet_name;
exports.NetworkRe = NetworkRe;
/* No side effect */
